# config
cover: /img/img-bg.jpg
logo: /img/logo.svg
bio: 'A developer, emacs user, free software enthusiast. Spends his time with his family and friends or as a consultant at ThoughtWorks. Likes chess, games and coding.'

# Content
excerpt_link: Read More

# Header  nav
menu:
  Home: /
  Archive: /archives
  # Wiki: /wiki/2014-10-28-wiki/
  # Favorites: /favorites
  Github: https://github.com/marcwebbie
  Twitter: https://twitter.com/marcwebbie
  # Linkedin: https://br.linkedin.com/in/marcondessilva

##Private: /private

# nav.fonticon.css
navclass:
  Home: icon-home
  Archive: icon-news
  # Images: icon-image
  # Wiki: icon-wiki
  # Favorites: icon-Favorites
  Github: icon-github
  Twitter: icon-twitter
  # Linkedin: icon-linkedin

##Private: icon-lock
rss: /atom.xml

# Miscellaneous
# google_analytics: UA-58094309-1
google_analytics: UA-58207692-1
favicon: /favicon.png
twitter: marcwebbie
google_plus: marcwebbie@gmail.com
fb_admins:
fb_app_id:
